"""
Domain models for alerts generated by the system.

Alerts notify administrators of significant events or anomalies, such as
performance degradation or errors in data ingestion. They include a
severity level and a timestamp.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from ..common.enums import AlertLevel


@dataclass
class Alert:
    """Represents a system-generated alert."""

    id: int
    level: AlertLevel
    message: str
    created_at: datetime
    details: Optional[dict] = None